logger:
  compress: true
  max-age: 7
  max-size: 100
  max-backups: 10
  director: ./logs
  log-in-terminal: false
  show-line-number: false
system:
  app-name: json-server
  ip-validation-able: true
  query-split-able: true
  proxy-check-able: true
  port: 3001
  db-type: mysql
i18n:
  default-lng: zh-CN
  lngs:
    - zh-CN
  path: ./locales
cors:
  allow-methods:
    - GET
    - POST
    - PUT
    - DELETE
  allow-headers:
    - Content-Type
    - Authorization
  allow-credentials: true
  max-age: 12h
  allow-origins:
    - "*"
mysql:
  host: 192.168.1.2
  port: 3306
  username: root
  password: ljs.1017
  db-name: json_server
  default-string-size: 191
  dont-support-rename-column: true
  dont-support-rename-index: true
redis:
  host: 192.168.1.2
  port: 6379
  password: ljs.1017
  db: 0